{
 "title": "Surveillance Neptune kiosk",
 "description": "Neptune metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Analyzer on network",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count_ARM7{})/2\n+sum(count_ARM20{})/2\n+sum(count_ARM7p{})/2\n+sum(count_Other{})/2"
    }
   ]
  },
  {
   "title": "Analyzer in test",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(IDAnalyseur) FROM applicationqm"
    }
   ]
  },
  {
   "title": "Analyzer double check",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(IDAnalyseur) FROM serieqm WHERE QMStatus = 1 "
    }
   ]
  },
  {
   "title": "Occupancy rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT 'MP101M' as 'Analyser', 25 as 'Testing place'"
    },
    {
     "rawSql": "SELECT REGEXP_REPLACE(def.NomAnalyseur, \"_Bc\", \"\") as 'Analyser', SUM(rack.nbplace) as 'Testing place'\n\t\t\t\tFROM\n\t\t\t\t    listedefinitionanalyseur AS def,\n\t\t\t\t    qmrack as rack\n\t\t\t\tWHERE\n\t\t\t\t    rack.idtypeapp = def.idanalyseur\nGROUP BY NomAnalyseur, rack.nbplace, rack.idtypeapp"
    },
    {
     "rawSql": "SELECT NomAnalyseur as 'Analyser', COUNT(IDAnalyseur) as 'In test'\nFROM\n(SELECT qm.IDAnalyseur, def.NomAnalyseur\n\t\t\t\tFROM\n\t\t\t\t    applicationqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listeaffectation AS lsta,\n\t\t\t\t    listedefinitionanalyseur AS def,\n            apprack AS rack,\n            qmrack AS qmr\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lsta.NoSerieARM\n\t\t\t\t    AND lsta.NoSerieAnalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n            AND rack.idserieqm = qm.IDAnalyseur\n            AND qmr.id = rack.idRack\n            AND (qmr.visurack = 0 OR qmr.visurack IS null)\nGROUP BY qm.IDAnalyseur, def.NomAnalyseur) AS TOTO\nGROUP BY NomAnalyseur"
    },
    {
     "rawSql": "SELECT\n\"CNH3e\" AS 'Analyser',\nROUND (   \n        (\n            LENGTH(toto.Variable)\n            - LENGTH( REPLACE ( toto.Variable, \"CNH3-\", \"\") ) \n        ) / LENGTH(\"CNH3-\")        \n    ) AS 'In test' \nFROM\n(SELECT qm.IDAnalyseur , qm.Variable\n\t\t\t\tFROM\n\t\t\t\t    applicationqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listeaffectation AS lsta,\n\t\t\t\t    listedefinitionanalyseur AS def,\n            apprack AS rack,\n            qmrack AS qmr\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lsta.NoSerieARM\n\t\t\t\t    AND lsta.NoSerieAnalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n            AND rack.idserieqm = qm.IDAnalyseur\n            AND qmr.id = rack.idRack\n            AND def.NomAnalyseur LIKE '%NH3%'\nGROUP BY qm.IDAnalyseur, qm.Variable) AS toto"
    },
    {
     "rawSql": "SELECT\n\"CTRSe\" AS 'Analyser',\nROUND (   \n        (\n            LENGTH(toto.Variable)\n            - LENGTH( REPLACE ( toto.Variable, \"CTRS-\", \"\") ) \n        ) / LENGTH(\"CNH3-\")        \n    ) AS 'In test' \nFROM\n(SELECT qm.IDAnalyseur , qm.Variable\n\t\t\t\tFROM\n\t\t\t\t    applicationqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listeaffectation AS lsta,\n\t\t\t\t    listedefinitionanalyseur AS def,\n            apprack AS rack,\n            qmrack AS qmr\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lsta.NoSerieARM\n\t\t\t\t    AND lsta.NoSerieAnalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n            AND rack.idserieqm = qm.IDAnalyseur\n            AND qmr.id = rack.idRack\n            AND def.NomAnalyseur LIKE '%CTRS%'\nGROUP BY qm.IDAnalyseur, qm.Variable) AS toto"
    },
    {
     "rawSql": "SELECT NomAnalyseur as 'Analyser', COUNT(IDAnalyseur) as 'In test'\nFROM\n(SELECT qm.IDAnalyseur, def.NomAnalyseur\n\t\t\t\tFROM\n\t\t\t\t    applicationqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listeaffectation AS lsta,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lsta.NoSerieARM\n\t\t\t\t    AND lsta.NoSerieAnalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND def.NomAnalyseur = \"MP101M\"\nGROUP BY qm.IDAnalyseur, def.NomAnalyseur) AS TOTO\nGROUP BY NomAnalyseur"
    },
    {
     "rawSql": "SELECT REGEXP_REPLACE(NomAnalyseur, \"_Bc\", \"\") as 'Analyser', COUNT(IDAnalyseur) as 'Double check'\nFROM\n(SELECT qm.IDAnalyseur, def.NomAnalyseur\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.KeyAnalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n            AND qm.QMStatus = 1\n) AS TOTO\nGROUP BY NomAnalyseur"
    },
    {
     "rawSql": "SELECT REGEXP_REPLACE(NomAnalyseur, \"_Bc\", \"\") as 'Analyser', COUNT(IDAnalyseur) as 'To be verified'\nFROM\n(SELECT qm.IDAnalyseur, def.NomAnalyseur\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.KeyAnalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n            AND qm.QMStatus = 2\n) AS TOTO\nGROUP BY NomAnalyseur"
    }
   ]
  },
  {
   "title": "Analyzer to be verified",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(IDAnalyseur) FROM serieqm WHERE QMStatus = 2"
    }
   ]
  },
  {
   "title": "Activity per analyzer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "SELECT *, ((tmp.valid/tmp.nb)*100.0) as percent FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n        GROUP BY dt) AS tmp",
     "rawSql": "SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'All' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n        GROUP BY dt) AS tmp"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  AC32e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'AC32e' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"AC32e\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  AF22e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'AF22e' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"AF22e\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  CO12e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'CO12e' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"CO12e\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  MP101M FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'MP101M' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"MP101M\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  O342e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'O342e' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"O342e\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  CNH3e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'CNH3e' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"CNH3e\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  CTRSe FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'CTRSe' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"CTRSe\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Analyzer tested",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT fulldata.time_sec, Cumul FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'Cumul'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  AC32e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'AC32e'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"AC32e\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  AF22e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'AF22e'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"AF22e\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  CO12e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'CO12e'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"CO12e\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  MP101m FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'MP101m'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"MP101m\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  O342e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'O342e'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"O342e\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  CNH3e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'CNH3e'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"CNH3e\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  CTRSe FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'CTRSe'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"CTRSe\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    }
   ]
  }
 ]
}