{
 "title": "Surveillance Neptune",
 "description": "Neptune metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Neptune Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "expr": "topk(1, sum((node_time_seconds - node_boot_time_seconds) * on(instance) group_left(node_name) node_meta{}) by (node_name))"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(node_meta * on(instance) group_left(node_name) node_meta{})"
      }
     ]
    },
    {
     "title": "CPUs",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{mode=\"idle\"} * on(instance) group_left(node_name) node_meta{})"
      }
     ]
    },
    {
     "title": "CPU used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "100 - sum(irate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * on(instance) group_left(node_name) node_meta{}) * 100 / count(node_cpu_seconds_total{mode=\"user\"} * on(instance) group_left(node_name) node_meta{}) "
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes * on(instance) group_left(node_name) node_meta{})"
      }
     ]
    },
    {
     "title": "Memory used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "100-sum((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * on(instance) group_left(node_name) node_meta{} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{})"
      }
     ]
    }
   ]
  },
  { "title": "QM Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Analyzer on network",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(count_ARM7{})/2\n+sum(count_ARM20{})/2\n+sum(count_ARM7p{})/2\n+sum(count_Other{})/2"
    }
   ]
  },
  {
   "title": "Analyzer on network by board type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_ARM7{instance=\"172.16.1.91:9494\"})",
     "legendFormat": "ARM7"
    },
    {
     "expr": "sum(count_ARM20{instance=\"172.16.1.91:9494\"})",
     "legendFormat": "ARM20"
    },
    {
     "expr": "sum(count_ARM7p{instance=\"172.16.1.91:9494\"})",
     "legendFormat": "ARM7+"
    },
    {
     "expr": "sum(count_Other{instance=\"172.16.1.91:9494\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Analyzer in test",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(IDAnalyseur) AS v FROM applicationqm"
    },
    {
     "rawSql": "SELECT\nROUND (   \n        (\n            LENGTH(toto.Variable)\n            - LENGTH( REPLACE ( toto.Variable, \"CNH3-\", \"\") ) \n        ) / LENGTH(\"CNH3-\")        \n    )-1 AS 'v'\nFROM\n(SELECT qm.IDAnalyseur , qm.Variable\n\t\t\t\tFROM\n\t\t\t\t    applicationqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listeaffectation AS lsta,\n\t\t\t\t    listedefinitionanalyseur AS def,\n            apprack AS rack,\n            qmrack AS qmr\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lsta.NoSerieARM\n\t\t\t\t    AND lsta.NoSerieAnalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n            AND rack.idserieqm = qm.IDAnalyseur\n            AND qmr.id = rack.idRack\n            AND def.NomAnalyseur LIKE '%NH3%'\nGROUP BY qm.IDAnalyseur, qm.Variable) AS toto"
    },
    {
     "rawSql": "SELECT\nROUND (   \n        (\n            LENGTH(toto.Variable)\n            - LENGTH( REPLACE ( toto.Variable, \"CTRS-\", \"\") ) \n        ) / LENGTH(\"CTRS-\")        \n    )-1 AS 'v'\nFROM\n(SELECT qm.IDAnalyseur , qm.Variable\n\t\t\t\tFROM\n\t\t\t\t    applicationqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listeaffectation AS lsta,\n\t\t\t\t    listedefinitionanalyseur AS def,\n            apprack AS rack,\n            qmrack AS qmr\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lsta.NoSerieARM\n\t\t\t\t    AND lsta.NoSerieAnalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n            AND rack.idserieqm = qm.IDAnalyseur\n            AND qmr.id = rack.idRack\n            AND def.NomAnalyseur LIKE '%TRS%'\nGROUP BY qm.IDAnalyseur, qm.Variable) AS toto"
    }
   ]
  },
  {
   "title": "Occupancy rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT 'MP101M' as 'Analyser', 25 as 'Testing place'"
    },
    {
     "rawSql": "SELECT REGEXP_REPLACE(def.NomAnalyseur, \"_Bc\", \"\") as 'Analyser', SUM(rack.nbplace) as 'Testing place'\n\t\t\t\tFROM\n\t\t\t\t    listedefinitionanalyseur AS def,\n\t\t\t\t    qmrack as rack\n\t\t\t\tWHERE\n\t\t\t\t    rack.idtypeapp = def.idanalyseur\nGROUP BY NomAnalyseur, rack.nbplace, rack.idtypeapp"
    },
    {
     "rawSql": "SELECT NomAnalyseur as 'Analyser', COUNT(IDAnalyseur) as 'In test'\nFROM\n(SELECT qm.IDAnalyseur, def.NomAnalyseur\n\t\t\t\tFROM\n\t\t\t\t    applicationqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listeaffectation AS lsta,\n\t\t\t\t    listedefinitionanalyseur AS def,\n            apprack AS rack,\n            qmrack AS qmr\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lsta.NoSerieARM\n\t\t\t\t    AND lsta.NoSerieAnalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n            AND rack.idserieqm = qm.IDAnalyseur\n            AND qmr.id = rack.idRack\n            AND (qmr.visurack = 0 OR qmr.visurack IS null)\nGROUP BY qm.IDAnalyseur, def.NomAnalyseur) AS TOTO\nGROUP BY NomAnalyseur"
    },
    {
     "rawSql": "SELECT\n\"CNH3e\" AS 'Analyser',\nROUND (   \n        (\n            LENGTH(toto.Variable)\n            - LENGTH( REPLACE ( toto.Variable, \"CNH3-\", \"\") ) \n        ) / LENGTH(\"CNH3-\")        \n    ) AS 'In test' \nFROM\n(SELECT qm.IDAnalyseur , qm.Variable\n\t\t\t\tFROM\n\t\t\t\t    applicationqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listeaffectation AS lsta,\n\t\t\t\t    listedefinitionanalyseur AS def,\n            apprack AS rack,\n            qmrack AS qmr\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lsta.NoSerieARM\n\t\t\t\t    AND lsta.NoSerieAnalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n            AND rack.idserieqm = qm.IDAnalyseur\n            AND qmr.id = rack.idRack\n            AND def.NomAnalyseur LIKE '%NH3%'\nGROUP BY qm.IDAnalyseur, qm.Variable) AS toto"
    },
    {
     "rawSql": "SELECT\n\"CTRSe\" AS 'Analyser',\nROUND (   \n        (\n            LENGTH(toto.Variable)\n            - LENGTH( REPLACE ( toto.Variable, \"CTRS-\", \"\") ) \n        ) / LENGTH(\"CNH3-\")        \n    ) AS 'In test' \nFROM\n(SELECT qm.IDAnalyseur , qm.Variable\n\t\t\t\tFROM\n\t\t\t\t    applicationqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listeaffectation AS lsta,\n\t\t\t\t    listedefinitionanalyseur AS def,\n            apprack AS rack,\n            qmrack AS qmr\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lsta.NoSerieARM\n\t\t\t\t    AND lsta.NoSerieAnalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n            AND rack.idserieqm = qm.IDAnalyseur\n            AND qmr.id = rack.idRack\n            AND def.NomAnalyseur LIKE '%CTRS%'\nGROUP BY qm.IDAnalyseur, qm.Variable) AS toto"
    },
    {
     "rawSql": "SELECT NomAnalyseur as 'Analyser', COUNT(IDAnalyseur) as 'In test'\nFROM\n(SELECT qm.IDAnalyseur, def.NomAnalyseur\n\t\t\t\tFROM\n\t\t\t\t    applicationqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listeaffectation AS lsta,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lsta.NoSerieARM\n\t\t\t\t    AND lsta.NoSerieAnalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND def.NomAnalyseur = \"MP101M\"\nGROUP BY qm.IDAnalyseur, def.NomAnalyseur) AS TOTO\nGROUP BY NomAnalyseur"
    },
    {
     "rawSql": "SELECT REGEXP_REPLACE(NomAnalyseur, \"_Bc\", \"\") as 'Analyser', COUNT(IDAnalyseur) as 'Double check'\nFROM\n(SELECT qm.IDAnalyseur, def.NomAnalyseur\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.KeyAnalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n            AND qm.QMStatus = 1\n) AS TOTO\nGROUP BY NomAnalyseur"
    },
    {
     "rawSql": "SELECT REGEXP_REPLACE(NomAnalyseur, \"_Bc\", \"\") as 'Analyser', COUNT(IDAnalyseur) as 'To be verified'\nFROM\n(SELECT qm.IDAnalyseur, def.NomAnalyseur\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.KeyAnalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n            AND qm.QMStatus = 2\n) AS TOTO\nGROUP BY NomAnalyseur"
    }
   ]
  },
  {
   "title": "Analyzer double check",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(IDAnalyseur) FROM serieqm WHERE QMStatus = 1 "
    }
   ]
  },
  {
   "title": "Analyzer to be verified",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(IDAnalyseur) FROM serieqm WHERE QMStatus = 2"
    }
   ]
  },
  {
   "title": "Valid test in one pass by analyzer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "SELECT *, ((tmp.valid/tmp.nb)*100.0) as percent FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n        GROUP BY dt) AS tmp",
     "rawSql": "SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'All' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n        GROUP BY dt) AS tmp"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  AC32e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'AC32e' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"AC32e\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  AF22e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'AF22e' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"AF22e\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  CO12e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'CO12e' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"CO12e\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  MP101M FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'MP101M' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"MP101M\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  O342e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'O342e' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"O342e\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  CNH3e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'CNH3e' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"CNH3e\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  CTRSe FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(dt, \"%Y-%m-%d\") AS time_sec, ((tmp.valid/(tmp.valid+tmp.rem))*100.0) as 'CTRSe' FROM \n\t\t\t\t(SELECT\n\t\t\t\t\tDATE_FORMAT(qm.dateQM, \"%Y-%m-01\") as dt,\n\t\t\t\t\tSUM(IF(qm.qmstatus=0,1,0)) as valid,\n\t\t\t\t\tSUM(IF(qm.qmstatus=3,1,0)) as rem,\n\t\t\t\t\tcount(qm.qmstatus) AS nb\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"CTRSe\"\n        GROUP BY dt) AS tmp) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Analyzer tested",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT fulldata.time_sec, Cumul FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'Cumul'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  AC32e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'AC32e'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"AC32e\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  AF22e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'AF22e'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"AF22e\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  CO12e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'CO12e'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"CO12e\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  MP101m FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'MP101m'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"MP101m\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  O342e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'O342e'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"O342e\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  CNH3e FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'CNH3e'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"CNH3e\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    },
    {
     "rawSql": "SELECT fulldata.time_sec,  CTRSe FROM\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec FROM serieqm as qm WHERE qm.dateQM >= $__timeFrom() GROUP BY time_sec) AS fulldata\nLEFT JOIN\n(SELECT STR_TO_DATE(DATE_FORMAT(qm.dateQM, \"%Y-%m-01\"), \"%Y-%m-%d\") AS time_sec, COUNT(lst.keyanalyseur) as 'CTRSe'\n\t\t\t\tFROM\n\t\t\t\t    serieqm as qm,\n\t\t\t\t    listeanalyseur as lst,\n\t\t\t\t    listedefinitionanalyseur AS def\n\t\t\t\tWHERE\n\t\t\t\t    qm.QMStatus = 0\n\t\t\t\t    AND qm.IDanalyseur = lst.keyanalyseur\n\t\t\t\t    AND lst.IDanalyseur = def.idanalyseur\n\t\t\t\t    AND qm.dateQM >= $__timeFrom()\n\t\t\t\t    AND def.NomAnalyseur = \"CTRSe\"\n        GROUP BY time_sec) AS filterdata\nON fulldata.time_sec = filterdata.time_sec ORDER BY time_sec"
    }
   ]
  },
  {
   "title": "Load Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load5 * on(instance) group_left(node_name) node_meta{}",
       "legendFormat": "load5 {{node_name}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])  * on(instance) group_left(node_name) node_meta{} * 100) by (node_name))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "CPU usage by Service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace=~\"neptune|voc\", id=~\"/docker/.*\"}[1m])) by (container_label_com_docker_swarm_service_name) * 100 ",
       "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_disk_read_bytes_total[1m]) * on(instance) group_left(node_name) node_meta{}) by (node_name)",
       "legendFormat": "Read {{node_name}}"
      },
      {
       "expr": "sum(irate(node_disk_written_bytes_total[1m]) * on(instance) group_left(node_name) node_meta{}) by (node_name)",
       "legendFormat": "Written {{node_name}}"
      }
     ]
    },
    {
     "title": "Containers Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{}[1m]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) node_meta) by (node_name)",
       "legendFormat": "IN {{node_name}}"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{}[1m]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) node_meta) by (node_name)",
       "legendFormat": "OUT {{node_name}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes - node_memory_Slab_bytes) * on(instance) group_left(node_name) node_meta{}) by (node_name)",
       "legendFormat": "Used {{node_name}}"
      },
      {
       "expr": "sum(node_memory_Cached * on(instance) group_left(node_name) node_meta{}) by (node_name)",
       "legendFormat": "Cached {{node_name}}"
      }
     ]
    },
    {
     "title": "Memory used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100-sum((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * on(instance) group_left(node_name) node_meta{} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{})",
       "legendFormat": "Memory used"
      }
     ]
    },
    {
     "title": "Memory usage by Service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum((node_meta{node_name=\"neptune1\"} * on(container_label_com_docker_swarm_node_id) group_right(job,instance) container_memory_usage_bytes{container_label_com_docker_stack_namespace=~\"neptune|voc\", id=~\"/docker/.*\"})) by (container_label_com_docker_swarm_service_name)",
       "legendFormat": "{{container_label_com_docker_swarm_service_name}} (neptune1)"
      },
      {
       "expr": "sum((node_meta{node_name=\"neptune2\"} * on(container_label_com_docker_swarm_node_id) group_right(job,instance) container_memory_usage_bytes{container_label_com_docker_stack_namespace=~\"neptune|voc\", id=~\"/docker/.*\"})) by (container_label_com_docker_swarm_service_name)",
       "legendFormat": "{{container_label_com_docker_swarm_service_name}} (neptune2)"
      }
     ]
    }
   ]
  }
 ]
}